### ISSUE TITLE
The results for the mesh itself looks very weird + request for mesh interpenetration loss addition

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/phosa#14]
Hi Jason,

I got the following results and I was wondering if you could answer any of the followings:
1. Why is the bike mesh looks so weird? Do you have any suggestion how to fix it? I am not sure why it is rotated 180 degrees.
2. Could you please release the code for mesh interpenetration loss?
3. Do you know why not all the people in the side view are present in the top view?

![000000038829_top](https://user-images.githubusercontent.com/1892917/101542449-c4742b00-3970-11eb-8332-12f028315605.jpg)
![000000038829](https://user-images.githubusercontent.com/1892917/101542450-c4742b00-3970-11eb-8a04-dbe264ab5d47.jpg)

**Comment by monajalal** [comment]
I also tried it on the following image and the results were quite weird. By the way, how can I make it such that it use female or male versus neutral mesh for human? I know SMPL-X has these models.

My other question is what happens when the bike in 2D image is not the same exact bike as in the 3D model from 3D warehouse. How can you handle that neural mesh fitting?


![kid_bike](https://user-images.githubusercontent.com/1892917/101551205-af9e9400-397e-11eb-8afd-c508dce59379.jpg)

![kid_bike](https://user-images.githubusercontent.com/1892917/101551226-b6c5a200-397e-11eb-845c-1a9765b7601b.jpg)
![kid_bike_top](https://user-images.githubusercontent.com/1892917/101551229-b9c09280-397e-11eb-967f-fcc32a026d6b.jpg)

**Comment by monajalal** [comment]
do you know how I can fix the rotation problem @jasonyzhang ?

**Comment by jasonyzhang** [comment]
Hi,

1. If the mask predictions from PointRend look reasonable, then it is likely that you are not running for enough initializations. What are you setting for `num_initializations`? The default parameters in the Colab notebook should be a reasonable starting point.
2. I used https://github.com/vchoutas/torch-mesh-isect. However, this approach easily gets stuck in local minima. I would recommend using an SDF implementation such as [this one](https://github.com/JiangWenPL/multiperson/tree/master/sdf). If you wish to use torch-mesh-isect, add the following code:

```
        # Add this to the __init__ of Losses
        # Mesh Interpenetration stuff.
        bs, nv = verts_combined.shape[:2]
        bs, nf = faces.shape[:2]
        self.faces_idx = (
            faces + (torch.arange(bs, dtype=torch.long).cuda() * nv)[:, None, None]
        )
        # Create the search tree
        MAX_COLLISIONS = 5000  # Increase if get CUDA error about illegal memory.
        SIGMA = 0.5  # The height of the cone used to calculate the distance field loss.
        POINT_TO_PLANE = False  # Use point to distance
        self.search_tree = BVH(max_collisions=MAX_COLLISIONS)
        self.pen_distance = collisions_loss.DistanceFieldPenetrationLoss(
            sigma=SIGMA, point2plane=POINT_TO_PLANE, vectorized=True
        )
```
```
    # Add this to the Losses class
    def compute_collision_loss(self, verts_combined, num_instances):
        triangles = verts_combined.view([-1, 3])[self.faces_idx]
        with torch.no_grad():
            collision_idxs = self.search_tree(triangles)
        loss_coll = self.pen_distance(triangles, collision_idxs).mean() / num_instances
        return {"loss_collision": loss_coll}
```
```
            # Add this to forward of Model class
            if loss_weights is None or loss_weights["lw_collision"] > 0:
            loss_dict.update(self.losses.compute_collision_loss(
                verts_combined=combine_verts(
                    [verts_object, verts_person[:, self.verts_id_subsampled]]
                ),
                num_instances=(len(verts_object) + len(verts_person)),
            ))
```

3. You can set the top-down viewpoint here. The other people are not visible because they are not close to the bike in 3D space. https://github.com/facebookresearch/phosa/blob/74d7c99a5a3d6804219445f0d22ca97f8ddf6989/phosa/global_opt.py#L656-L660.

Best,
Jason

**Comment by monacv** [comment]
hmmm not sure what happened in between but did you add the code for mesh intersect and rotation? the new push apparently had everything fixed :)
![Screenshot from 2020-12-23 19-02-54](https://user-images.githubusercontent.com/76495162/103045218-a2260400-4551-11eb-966b-c737cd32cb57.png)

**Comment by ocissor** [comment]
Hi, I am trying to incorporate the mesh interpenetration loss and was going through your solution can you please explain what is vert_combined(my understanding is that you stacked the human and object vertices) and how to make it also regarding the faces is it also the combined one like human + object? what are bs, nv and nf.
Thank you

**Comment by ocissor** [comment]
> Hi,
> 
> 1. If the mask predictions from PointRend look reasonable, then it is likely that you are not running for enough initializations. What are you setting for `num_initializations`? The default parameters in the Colab notebook should be a reasonable starting point.
> 2. I used https://github.com/vchoutas/torch-mesh-isect. However, this approach easily gets stuck in local minima. I would recommend using an SDF implementation such as [this one](https://github.com/JiangWenPL/multiperson/tree/master/sdf). If you wish to use torch-mesh-isect, add the following code:
> 
> ```
>         # Add this to the __init__ of Losses
>         # Mesh Interpenetration stuff.
>         bs, nv = verts_combined.shape[:2]
>         bs, nf = faces.shape[:2]
>         self.faces_idx = (
>             faces + (torch.arange(bs, dtype=torch.long).cuda() * nv)[:, None, None]
>         )
>         # Create the search tree
>         MAX_COLLISIONS = 5000  # Increase if get CUDA error about illegal memory.
>         SIGMA = 0.5  # The height of the cone used to calculate the distance field loss.
>         POINT_TO_PLANE = False  # Use point to distance
>         self.search_tree = BVH(max_collisions=MAX_COLLISIONS)
>         self.pen_distance = collisions_loss.DistanceFieldPenetrationLoss(
>             sigma=SIGMA, point2plane=POINT_TO_PLANE, vectorized=True
>         )
> ```
> 
> ```
>     # Add this to the Losses class
>     def compute_collision_loss(self, verts_combined, num_instances):
>         triangles = verts_combined.view([-1, 3])[self.faces_idx]
>         with torch.no_grad():
>             collision_idxs = self.search_tree(triangles)
>         loss_coll = self.pen_distance(triangles, collision_idxs).mean() / num_instances
>         return {"loss_collision": loss_coll}
> ```
> 
> ```
>             # Add this to forward of Model class
>             if loss_weights is None or loss_weights["lw_collision"] > 0:
>             loss_dict.update(self.losses.compute_collision_loss(
>                 verts_combined=combine_verts(
>                     [verts_object, verts_person[:, self.verts_id_subsampled]]
>                 ),
>                 num_instances=(len(verts_object) + len(verts_person)),
>             ))
> ```
> 
> 3. You can set the top-down viewpoint here. The other people are not visible because they are not close to the bike in 3D space. https://github.com/facebookresearch/phosa/blob/74d7c99a5a3d6804219445f0d22ca97f8ddf6989/phosa/global_opt.py#L656-L660
>    .
> 
> Best, Jason

Hi, I am trying to incorporate the mesh interpenetration loss and was going through your solution can you please explain what is vert_combined and how to make it also regarding the faces is it also the combined one like human + object? what are bs, nv and nf.
Thank you

**Comment by jasonyzhang** [comment]
Hi,

bs = batch size
nv = number of vertices
nf = number of faces

Essentially, you need all your meshes to be combined into a single mesh. For example, you may have a mesh with vertices NV1x3 and faces NF1x3 and another mesh with vertices NV2x3 and faces NF2x3. You want a combined mesh with vertices (NV1+NV2)x3 and faces (NF1+NF2). In general, you can directly concatenate vertices, but the faces need to be re-indexed so that each face index corresponds to the correct set of vertices.

Still though, I would recommend using something like [this](https://github.com/JiangWenPL/multiperson/tree/master/sdf) to avoid local minima.

**Comment by ocissor** [comment]
> Hi,
> 
> bs = batch size nv = number of vertices nf = number of faces
> 
> Essentially, you need all your meshes to be combined into a single mesh. For example, you may have a mesh with vertices NV1x3 and faces NF1x3 and another mesh with vertices NV2x3 and faces NF2x3. You want a combined mesh with vertices (NV1+NV2)x3 and faces (NF1+NF2). In general, you can directly concatenate vertices, but the faces need to be re-indexed so that each face index corresponds to the correct set of vertices.
> 
> Still though, I would recommend using something like [this](https://github.com/JiangWenPL/multiperson/tree/master/sdf) to avoid local minima.

Hello, thank you very much for your response, by any chance are you aware of how to incorporate the SDF loss mentioned here https://github.com/JiangWenPL/multiperson/tree/master/sdf in PHOSA codebase and how are the translations for humans being calculated?
Thank you.
