### ISSUE TITLE
Discrepancy between running the jupyter notebook locally vs using the Colab version

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/phosa#15]
Do you know what is the reason for the discrepancy in results I get from running the Jupyter notebook locally vs on Google colab?

local results:
![local_results](https://user-images.githubusercontent.com/1892917/101551828-b4b01300-397f-11eb-8764-474f0301c8a0.png)

colab results:
![colab_results](https://user-images.githubusercontent.com/1892917/101551848-baa5f400-397f-11eb-9be6-f5df05ed0068.png)

I have:
```
(base) mona@mona:~/research/phosa$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.6.0'
>>> import detectron2
>>> detectron2.__version__
'0.3'
>>> import neural_renderer as nr
>>> nr.__version__
'1.1.3'


```

**Comment by jasonyzhang** [comment]
The colab notebook uses detectron2 version 0.2.1 and pytorch version 1.4.0. You may want to try installing those versions to be equivalent.

If you are inclined to stick with detectron2 version 0.3, try cloning from master in external/detectron2. (Currently, it is likely that you have cloned 0.2.1 but your installed package is 0.3)

**Comment by ppwwyyxx** [comment]
According to the code:
https://github.com/facebookresearch/phosa/blob/74d7c99a5a3d6804219445f0d22ca97f8ddf6989/phosa/constants.py#L8-L14

It hard-coded the path to a (old) pointrend model file, and the path to the pointrend config in the detectron2 repo.

Detectron2 has updated the config in its repo and also provided a new model file corresponding to it. Therefore there is a mismatch.

**Comment by monajalal** [comment]
@ppwwyyxx could you kindly please guide how I could fix this? which lines should I remove from phosa/phosa/constants.py if I want to use the PyTorch 1.6 and Detectron2 version 0.3?
Thanks a lot for having a look :)

**Comment by ppwwyyxx** [comment]
A quick workaround is to replace the weights by a new model in https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend/#coco

**Comment by monajalal** [comment]
Thank you so much @ppwwyyxx  now it is fixed after changing the constant.py to the following (please let me know if I might have changed wrongly):

```
POINTREND_CONFIG = osp.join(
    POINTREND_PATH, "configs/InstanceSegmentation/pointrend_rcnn_X_101_32x8d_FPN_3x_coco.yaml"
)
POINTREND_MODEL_WEIGHTS = (
    "/home/mona/research/phosa/model_final_ba17b9.pkl"
)

```

![Screenshot_2020-12-09_20-37-10](https://user-images.githubusercontent.com/1892917/101709931-74739200-3a5e-11eb-8a99-d11025a3a63b.png)
