### ISSUE TITLE
undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

### ISSUE THREAD

**Issue by ffiioonnaa** [facebookresearch/phosa#2]
Hi,
Thanks  for your work, it's really impressive. When I run the demo, I encountered this error:

ImportError: /home/anaconda3/envs/phosa/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

Can you tell me how to solve it?

Thanks again!

**Comment by ffiioonnaa** [comment]
I solved it ,it was caused by the version of Neural Mesh Renderer. I  solved it by using the version of the code that is in the branch gh_pages. So I close this issue.

**Comment by pfvaldez** [comment]
@ffiioonnaa 

Can I ask for clarification. When I checked the branch 'gh_pages' there is no code?

![gh_pages](https://user-images.githubusercontent.com/16838175/116764371-7bbe2b00-aa53-11eb-95e0-ed89a972fe8b.png)

**Comment by jasonyzhang** [comment]
This can sometimes happen if the version of Pytorch you are using is not the one used to build NMR.  Try re-building NMR from source. https://github.com/facebookresearch/phosa#setting-up-external-dependencies
