### ISSUE TITLE
How can I reproduce the results in Table 1?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#20]
I am interested in reproducing the results in Table 1. Could you please guide me what are the steps in doing so? So far I have been able to run the demo on some images and get sensible results.

![Screenshot from 2021-03-15 18-48-08](https://user-images.githubusercontent.com/76495162/111231143-24591e00-85bf-11eb-91ab-677e0232243f.png)

**Comment by jasonyzhang** [comment]
Hi,

I just posted the code to run the web interface for our forced choice evaluation here: https://github.com/jasonyzhang/annotator

The evaluation is qualitative, so you (or someone else) will need to determine preference between two different images at a time. 

To generate the images for the independent composition, you can run the existing code as is for 0 iterations.
To generate the images for ours (which is what each row gets compared with), you can run the existing code for the full number of iterations.
To generate the images corresponding to each ablation, set that loss term to 0, and then run the existing code for the full number of iterations.

The filenames of the generated images should begin with the image id.

The COCO test set ids for the images used for the evaluation are [here](https://github.com/facebookresearch/phosa/blob/master/doc/evaluation_ids.json).

I am also happy to email you the rendered images that were used in the evaluation (the contains of the `ablations` folder for the annotator)

Best,
Jason

**Comment by monacv** [comment]
Thank you so much. This was very valuable to know.
