### ISSUE TITLE
How do you annotate the surface regions on the SMPL mesh and the 3D object meshes where it is likely to be an interaction?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#21]
Could you please guide me on which module in the code does the following or how do you exactly do it? 

**“Humans generally interact with objects in specific ways. For example, humans hold tennis rackets by the handle. This can be used as a strong prior for human-object interaction and adjust their spatial arrangement. To do this, we annotate surface regions on the SMPL mesh and on our 3D object meshes where there is likely to be interaction, similar to PROX”**

Do you have some screenshots to illustrate this process or a videocast so I could reproduce it on my own data?

**Comment by jasonyzhang** [comment]
We color-code parts of the interaction regions on the person and object using MeshLab. Figure 5 is a good example of how we color different parts.

Here's one possible way to paint on the object mesh in MeshLab:
1. Use the Z-painting tool to paint regions of the object mesh
2. Export the mesh using the wrl format
3. Access the per-vertex colors in the .wrl. The vertex indices corresponding to each color with correspond to a specific part.

**Comment by monacv** [comment]
**As for part 3, could you please share your script that does this?** 

I am not exactly sure how I should go about processing a wrl file. My produced wrl file after z-painting some of the vertices looks like this:

![Screenshot from 2021-03-29 19-00-45](https://user-images.githubusercontent.com/76495162/112910370-36f44c80-90c1-11eb-8252-6f102c90d519.png)

**Comment by jasonyzhang** [comment]
Color contains a list of colors indexed by vertex index. The vertex indices that correspond to "0 1 0" correspond to the region your selected.
