### ISSUE TITLE
Can I run phosa without providing the surface annotation json files?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#26]
I was wondering if I could run PHOSA without providing the surface annotation json files and if so, would you please be able to guide me a bit how to do so?

I can see they are requires here in constant.py file:

```
# Dict[class_name: List[Tuple(path_to_parts_json, interaction_pairs_dict)]].
PART_LABELS = {
    "person": [("models/meshes/person_labels.json", {})],
    "bicycle": [
        (
            "models/meshes/bicycle_01_labels.json",
            {"seat": ["butt"], "handle": ["lhand", "rhand"]},
        )
    ],
}
```

**Comment by monacv** [comment]
for example, I see that you are using bottle and wine glasses in phosa/constants.py file but there's no model or body part definition. 

Does it mean that you can also run phosa without the need for JSON files for surface annotation and body part segmentation correspondence? If so, could you please tell me how you do this? Thanks a lot.

![Screenshot from 2021-03-29 19-05-22](https://user-images.githubusercontent.com/76495162/112910689-e6c9ba00-90c1-11eb-986b-9eda9cd9e6a9.png)

**Comment by jasonyzhang** [comment]
Yes, you can create a "dummy" part that maps to all the vertices of the object. For instance, if your object has 1000 vertices, you can make your parts label json contain a dictionary mapping "dummy" to np.arange(1000). Then, in your interaction parts labeling, you can assign "dummy" to the corresponding person parts.
