### ISSUE TITLE
Why isn't the top view captured?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#31]
Could you please guide me and provide me with some tips on why the top view is not captured in your opinion? 

The middle image that is blank/white is the top view.

![tennis44_top](https://user-images.githubusercontent.com/76495162/113394130-b43feb80-9365-11eb-8fb5-b2a0214d7b26.jpg)
![tennis44](https://user-images.githubusercontent.com/76495162/113394132-b43feb80-9365-11eb-9046-b7ea31d8d118.jpg)
![tennis44](https://user-images.githubusercontent.com/76495162/113394152-bbff9000-9365-11eb-9313-88af66ea83f5.jpg)
![Screenshot from 2021-04-02 03-44-43](https://user-images.githubusercontent.com/76495162/113394179-c6218e80-9365-11eb-9942-1236076c6180.png)

**Comment by jasonyzhang** [comment]
The top camera probably is not properly aligned with the meshes. You can change the camera parameters here:
https://github.com/facebookresearch/phosa/blob/d2aa89dd786bfe27925fcb96e4615706c0c6b2d6/phosa/global_opt.py#L650-L666
