### ISSUE TITLE
How do you get the size distribution from human interaction? Can you release the code

### ISSUE THREAD

**Issue by HanHan55** [facebookresearch/phosa#32]
![image](https://user-images.githubusercontent.com/59916865/113799796-59086180-9788-11eb-902a-2ae0f38ca9b9.png)

1. could you release the code about the 'Learned size distribution from human interaction'?

2. And then I want to get the prior from my own data, like scale,camera pose.what should I do?

Thanks.

**Comment by jasonyzhang** [comment]
Hi,

I have updated the code to add the option to export the optimized parameters:
https://github.com/facebookresearch/phosa/blob/207a6b1754b80115dbbcb9d8abb9005b11e01f1f/phosa/global_opt.py#L561-L576

If you run `python demo.py --save_metadata`, it will export the intrinsic scales and pose parameters to json. To convert intrinsic scale to metric size in meters, multiply by 2. Note that we assume identity camera, so all poses are object-centric.

To compute the learned size distribution from human interaction, we run the optimization for every image in the COCO test set per category. Then, we tally up the size distribution, which can be done by iterating over all the jsons and keeping track of all the scales.

To get a prior from your own data, follow the directions to add your own object category (if it isn't bicycle). You will need to initialize with some reasonable initial size of that object category. For example, if bicycles are usually about 2 meters long, you could initialize the scaling factor to be 2 / 2 = 1.

Best,
Jason

**Comment by HanHan55** [comment]
Hi,

Thank you for your reply.

1.Maybe I didn't describe my problem clearly, I hope the code about "we run the optimization for every image in the COCO test set per category",not "export the optimized parameters".

2.I want to get the initial scale and other constants priors from my own data.So I want to know that  how you get the constants in constants.py?

Thanks again.

Best,
Han
