### ISSUE TITLE
How can I make phosa to work for Egocentric datasets or where human is very occluded/partially visible?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#35]
Is there a rule of thumb on how much of a human should be visible to the camera in order for phosa to work?

Here I am interested in finding the 3D interaction of human and bottle. We can see human legs and hands and the bottle is detected correctly. However, the results are not good. The photo is a frame from Epic Kitchen 100 (2020) dataset. Please let me know if you might have any suggestion :)

![epic_kitchen_sample](https://user-images.githubusercontent.com/76495162/114254733-18bf0400-997f-11eb-8d3b-c541ed1a83fc.jpg)
![epic_kitchen_sample](https://user-images.githubusercontent.com/76495162/114254736-1e1c4e80-997f-11eb-97e4-1a636a0cfb81.jpg)

**Comment by jasonyzhang** [comment]
PHOSA is not proposing a new human reconstruction method but rather uses off-the-shelf predictions to model human-object interactions. If your focus is on such closeup views, consider using a human pose estimation approach such as [this one](https://crockwell.github.io/partial_humans/). Alternatively, if your focus is on hand-object interactions, consider looking at something like [this](https://people.eecs.berkeley.edu/~zhecao/rhoi/).

Best,
Jason
