### ISSUE TITLE
Is there a way to optimize the object fitting much better?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#36]
Hello Jason,

Is there a way I could improve the object matching and transformation optimization to the 2D instance segmentation mask from PointRed? For example, my object in the original image is obviously upward, but the fit/matched item is downward.

Thanks a lot for any tip.

![in1](https://user-images.githubusercontent.com/76495162/114956544-1819e800-9e2d-11eb-85ac-1d0303a55c25.jpg)

![out1](https://user-images.githubusercontent.com/76495162/114956530-12240700-9e2d-11eb-9637-acf84e4a842f.jpg)

**Comment by jasonyzhang** [comment]
I am a bit surprised that the object fit is flipped. What does the mask look like? My guess is that very little of the pan handle was detected by PointRend.
