### ISSUE TITLE
How can I have the 2D bounding box of lifted 3D model for human and object separately?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/phosa#39]
Do you know if there is a way that after 3D shape of the human and object is created, I could reproject them to 2D and get the 2D bounding boxes encompassing each of the human as well as the object?

**Comment by jasonyzhang** [comment]
The 2D bounding boxes of the humans and objects are taken as inputs predicted from the object detector.  You can access theme here:
https://github.com/facebookresearch/phosa/blob/513e4f0c85134d1b79773787e4c269f05b9bf775/demo.py#L116
https://github.com/facebookresearch/phosa/blob/513e4f0c85134d1b79773787e4c269f05b9bf775/phosa/pose_optimization.py#L380

If you specifically want the projected 3D bounding boxes to 2D at the end of optimization, you can do something like:
```python
verts_object = model.get_verts_object()
verts_person = model.get_verts_person()
bboxes_object = phosa.global_opt.project_bbox(verts_object, model.renderer)
bboxes_person = phosa.global_opt.project_bbox(verts_person , model.renderer)
```
