### ISSUE TITLE
How can I get the 3D representation?

### ISSUE THREAD

**Issue by nessessence** [facebookresearch/phosa#41]
1. How can I get the 3D representation file after performing inference?
From the Colab, I just got the visualization of 3D construction projected on the 2D images. 
2. Could you explain the human parameters: ['bboxes', 'cams', 'faces', 'local_cams', 'verts', 'masks'] ?

Thanks

**Comment by jasonyzhang** [comment]
Hi,

If you want to export the 3D reconstruction as a mesh file, you can call `model.save_obj("export.obj")` which you can then download from colab and view using a mesh viewer (e.g. MeshLab).
https://github.com/facebookresearch/phosa/blob/513e4f0c85134d1b79773787e4c269f05b9bf775/phosa/global_opt.py#L578

The human parameters are:
* bboxes: 2D bounding boxes in xyxy format
* cams: Weak perspective camera (scale, tx, ty) w.r.t the whole image
* local_cams: Weak perspective camera w.r.t the bounding box crop
* verts: 3D vertices in a local coordinate system
* faces: mesh faces enumerating which vertices correspond to each face triangle
* masks: Predicted 2D masks from PointRend

Best,
Jason
