### ISSUE TITLE
Incompatibility with CUDA 11.0

### ISSUE THREAD

**Issue by purvaten** [facebookresearch/phosa#42]
Hi, I am running into issues while setting this codebase for CUDA 11.0 since it is not compatible with pytorch 1.4.

Specifically I am installing pytorch as follows: `conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=11.0 -c pytorch`.

But then I run into issues while installing `neural_renderer`, specifically `RuntimeError: Error compiling objects for extension `. I checked [several answers online](https://github.com/facebookresearch/maskrcnn-benchmark/issues/1236#issuecomment-632965456) and it seems that this error appears when using pytorch >= 1.5. I unfortunately cannot use that because of my CUDA driver restrictions.

Is there a solution to make it compatible for CUDA 11.0?

**Comment by purvaten** [comment]
This seems to be working with cudatoolkit 10.0, i.e., `conda install pytorch=1.4.0 torchvision=0.5.0 cudatoolkit=10.0 -c pytorch` as mentioned in the README.

But please update here in case there is a way to get this to work for a higher version of pytorch. Thanks!

**Comment by jasonyzhang** [comment]
Thanks, I've updated the README. If you wish to use a higher version of Pytorch, you can update all the `AT_CHECK`s to `TORCH_CHECK` in NMR. See #3.

Best,
JAson
