### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by MohsenAziz** [facebookresearch/phosa#43]
i got this error while running this line: segmenter = get_pointrend_predictor()

i think the problem is relevant to  the pickle file which has the weights, so could you help ?

**Comment by jasonyzhang** [comment]
Hi,

It looks like the detectron2 models have been updated and re-trained. I am now hosting the detectron2 weights directly, so this should no longer be a problem in the future.

Try re-pulling the code, and download the pre-trained PointRend as follows:
`wget -O models/model_final_3c3198.pkl https://github.com/jasonyzhang/data/blob/gh-pages/pointrend_model_final_3c3198.pkl?raw=True`

The project readme and colab notebook have been updated to reflect this change.

Best,
Jason
