### ISSUE TITLE
inputting own 3D pose model and object detector

### ISSUE THREAD

**Issue by smandava98** [facebookresearch/phosa#45]
Can I use this framework and put in my own custom pose model and object detector? If so, how can I experiment with this?

**Comment by jasonyzhang** [comment]
You can replace the human pose estimator here:

https://github.com/facebookresearch/phosa/blob/main/demo.py#L118-L124

and the segmentation model here:

https://github.com/facebookresearch/phosa/blob/main/demo.py#L111-L112

**Comment by smandava98** [comment]
Thanks Jason!

A followup:

Can the instance segmentation model be any 2d segmentation model like YOLO? And it would create 3D meshes from it automatically? A bit confused on how this works.

I am asking because I have a custom segmentation model that segments different objects.

Also my human pose estimator as long as it outputs SMPL parameters or would it have to output the meshes themselves?

**Comment by jasonyzhang** [comment]
You'll need an obj cad model corresponding to your object. The shape of the object will not be predicted. Rather, it is fitting the object pose according to the mask using the provided mesh.

The pose estimator should output the mesh itself. You can check out the bodymocap API if you need help with this.

**Comment by smandava98** [comment]
Oh I see now. Then this might not solve my use case. I essentially want to get object masks in world coordinates relevant to how humans interact with them and model that. It seems for this I need specific meshes for all those objects but those objects have an infinite number of shapes and sizes. I'll look deeper and see if there are any other solutions for this.
